packages:
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - sharp
  - unrs-resolver

pnpm:
  overrides:
    '@types/react': ^19.2.7
    react: ^19.2.3
    react-dom: ^19.2.3
