services:
  - name: artillery-calculator
    type: web
    runtime: docker
    rootDir: packages/mtc-artillery
    dockerContext: packages/mtc-artillery
    dockerfilePath: Dockerfile
    branch: dev
